---
name: Publish
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Publish on Github Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout entire git history
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'

      - name: Build Blog
        run: hugo --minify

      - name: Add CNAME file
        run: |
            echo "blog.aeddi.tech" > ./public/CNAME

      - name: Deploy on gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Create semantic-release config file
        run: |
          printf "module.exports = {
              plugins: [
                  '@semantic-release/commit-analyzer',
                  '@semantic-release/release-notes-generator',
                  '@semantic-release/github',
              ],
            };" > .releaserc.js

      - name: Create Github release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
